# Generated by Django 4.1.3 on 2022-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_class_coach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class", name="coach", field=models.CharField(max_length=50),
        ),
    ]
