# Generated by Django 4.1.3 on 2022-12-08 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0009_alter_classes_end_date_alter_classes_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="end_date",
            field=models.DateField(default=datetime.date(2022, 12, 8), null=True),
        ),
        migrations.AlterField(
            model_name="classes",
            name="end_time",
            field=models.TimeField(default=datetime.time(18, 1, 32, 879787), null=True),
        ),
        migrations.AlterField(
            model_name="classes",
            name="start_time",
            field=models.TimeField(default=datetime.time(18, 1, 32, 879787), null=True),
        ),
    ]
