# Generated by Django 4.1.3 on 2022-12-08 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0010_alter_classes_end_date_alter_classes_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="classes", name="end_date",),
        migrations.AlterField(
            model_name="classes",
            name="end_time",
            field=models.TimeField(default=datetime.time(18, 3, 9, 757296), null=True),
        ),
        migrations.AlterField(
            model_name="classes",
            name="start_time",
            field=models.TimeField(default=datetime.time(18, 3, 9, 757296), null=True),
        ),
    ]
