# Generated by Django 4.1.3 on 2022-12-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0012_classes_end_date_alter_classes_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="classes", name="end_date",),
        migrations.RemoveField(model_name="classes", name="end_time",),
        migrations.RemoveField(model_name="classes", name="start_time",),
    ]
