# Generated by Django 4.1.3 on 2022-11-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
