# Generated by Django 4.1.3 on 2022-11-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("accounts", "0015_alter_users_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="class_lst",
            field=models.ManyToManyField(default=None, to="classes.class"),
        ),
        migrations.AddField(
            model_name="users",
            name="classes",
            field=models.ManyToManyField(default=None, to="classes.classes"),
        ),
    ]
