# Generated by Django 4.1.3 on 2022-11-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_users_class_lst_users_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="password2",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
