# Generated by Django 4.1.3 on 2022-11-16 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('type', models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=7)),
            ],
        ),
    ]
