# Generated by Django 4.1.3 on 2022-11-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
