# Generated by Django 4.1.3 on 2022-11-17 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0004_usersubscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscriptions',
            old_name='subscriptio_id',
            new_name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
