# Generated by Django 4.1.3 on 2022-11-17 22:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0005_rename_subscriptio_id_usersubscriptions_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscriptions',
            new_name='StripeUsers',
        ),
    ]
