# Generated by Django 4.1.3 on 2022-11-18 00:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0009_rename_subscription_id_stripeusers_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeUsers',
            new_name='StripeUser',
        ),
    ]
