# Generated by Django 4.1.3 on 2022-11-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_ammenities_ammenityset_delete_ammenitieset_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ammenities',
            new_name='Ammenity',
        ),
    ]
