# Generated by Django 4.1.3 on 2022-11-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_rename_ammenities_ammenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studios/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='studio',
            name='images',
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studios.image')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studios.studio')),
            ],
        ),
        migrations.AddField(
            model_name='studio',
            name='images',
            field=models.ManyToManyField(to='studios.image'),
        ),
    ]
