# Generated by Django 4.1.3 on 2022-11-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_image_remove_studio_images_imageset_studio_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='images',
        ),
        migrations.AddField(
            model_name='studio',
            name='images',
            field=models.ManyToManyField(
                blank=True, related_name='ImageSet', through='studios.ImageSet', to='studios.image'),
        ),
    ]
