# Generated by Django 4.1.3 on 2022-12-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_alter_ammenityset_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='studios/images/'),
        ),
    ]
